# Generated by Django 5.0.3 on 2024-05-02 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='technology',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title',
        ),
    ]
