version: '3.12'

services:
  django:
    build: ./backend
    container_name: django_app
    command: gunicorn projects.wsgi:application --bind 0.0.0.0:8080
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./venv
    depends_on:
      - db

  db:
    image: oraclelinux:9
    container_name: oracle_db
    volumes:
      - oracle_data:/var/lib/oraclelinux/data
    environment:
      ORACLE_DB: your_db_name
      ORACLE_USER: your_db_user
      ORACLE_PASSWORD: your_db_password

volumes:
  postgres_data:
